### ISSUE TITLE
drawing on top of app

### ISSUE THREAD

**Issue by antimodular** [elliotwoods/ofxCeres#2]
along with your gui i am also using ofxGUI and draw a bunch of other 2d stuff on top.

but the your 3d world and some of your GUI elements place themselves infront of my stuff. :(
as a result my stuff either gets completely hidden or has some alpha applied to it.

your ofxCvGui::Builder gui;
seems to be called automatically, which means my draw() function might get called before your stuff. Which results in your stuff placing itself in front of mine.

Do you have a solution for this dilemma?

**Comment by elliotwoods** [comment]
if you think it's just draw order
then you can check out https://github.com/elliotwoods/ofxCvGui/blob/master/src/ofxCvGui/Controller.cpp#L19

and then instead of using the ofApp::draw() function, just make your own draw function and add a listener to ofEvents().draw to call it 

and perform that ofAddListener after gui.init()

**Comment by elliotwoods** [comment]
or just learn to use ofxCvGui and be happier for the rest of your life ;)

**Comment by antimodular** [comment]
Thank so much. This did the trick, now the ofxGui it drawn on top.

created 
```
void drawCustom(ofEventArgs & args);
```
and added to ofApp::setup() 
``` 
gui.init()
ofAddListener(ofEvents().draw, this, &ofApp::drawCustom);
```
Hopefully in the near future i will start a happier life with ofxCvGui :)
