### ISSUE TITLE
Cant compile Eigen Block.h issues

### ISSUE THREAD

**Issue by IS512** [elliotwoods/ofxCeres#4]
Haven't been able to compile any of the examples - Block.h kicks up a lot of issues - on Xcode 11.4.1

`Explicit specialization of undeclared template struct 'traits'`

`Expected ';' at end of declaration list`

for the below

`struct traits<Block<XprType, BlockRows, BlockCols, InnerPanel> > : traits<XprType>
{
  typedef typename traits<XprType>::Scalar Scalar;
  typedef typename traits<XprType>::StorageKind StorageKind;
  typedef typename traits<XprType>::XprKind XprKind;
  typedef typename ref_selector<XprType>::type XprTypeNested;
  typedef typename remove_reference<XprTypeNested>::type _XprTypeNested;`

**Comment by elliotwoods** [comment]
Interesting - this has been running on OSX
I don't have oF setup on OSX right now so sorry I can't help you
maybe @antimodular can help? (you had it running on osx right?)

**Comment by elliotwoods** [comment]
here's a version of ofxCeres which i had working in osx (whole oF folder)
https://www.dropbox.com/sh/v314fcev0gf5egr/AADbP2_koi9rjUNS82aPXpPha?dl=0

**Comment by stephanschulz** [comment]
compiling the `Example-MovingHead` works fine on my macOS systems.

But Example-MovingHeadAdvanced has a linker error due to ofxCvGui. 
I see ofxCvGui being declared in many places through the file inside the src folder.

Interestingly the above mentioned `Block` issue has not yet appeared.
```
  /Users/stephanschulz/Library/Developer/Xcode/DerivedData/Example_Simple2-fhqbajsapcmshgbxkoyidbtixczm/Build/Intermediates.noindex/Example_Simple2.build/Release/Example_Simple2.build/Objects-normal/x86_64/main.o
    /Users/stephanschulz/Library/Developer/Xcode/DerivedData/Example_Simple2-fhqbajsapcmshgbxkoyidbtixczm/Build/Intermediates.noindex/Example_Simple2.build/Release/Example_Simple2.build/Objects-normal/x86_64/pch_ofxCvGui.o
ld: 153 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
https://github.com/elliotwoods/ofxCeres/tree/master/Example-MovingHeadAdvanced/src

**Comment by stephanschulz** [comment]
But with the most recent ofxCeres version using the projectGenerator and the compiling  I also get the `Block` issue with the `Example-MovingHead` 
mh? Guess something change between the version. I will have to poke around and see.

**Comment by elliotwoods** [comment]
oh weird. i've only been developing in windows recently . you might be best rolling back to last version that worked with osx?

**Comment by stephanschulz** [comment]
noted.
I am interested to know why the older version seems to use the newer libceres.2.0.0.dylib and the newer version the older libceres.1.14.0.dylib.
I will look in to making your newer add-on version work a bit more. I assume that the more recent version has improvements such as working with glm::, and might work even better than the previous one?

**Comment by stephanschulz** [comment]
As you suggested I rolled back to my version from 2019.
I also created a collection of the addons that work currently work well together.
https://github.com/antimodular/movingHead

**Comment by elliotwoods** [comment]
You're right that the most recent version has better compatibility with GLM. That is also partially due to compiler flags (check ofxCeres.props), so would need to recreate that on OS X side also

**Comment by stephanschulz** [comment]
I managed to get of the `Block` error using my ofxCeres version with `libceres.2.0.0.dylib` on macOS 10.15.7, Xcode 12.4, OF 0.11.2

<img width="633" alt="Screen Shot 2021-12-04 at 7 19 06 PM" src="https://user-images.githubusercontent.com/1054816/144728715-999713c9-081b-4430-a149-dd278effe60c.png">


- I used projectGenerator on the Example-MovingHead.
- In Xcode in the navigation panels I removed the ceres folder so that all is left in the ofxCeres folder is miniglog and src
- then -> Project and Target Build settings -> Header Search Paths I removed all references to ofxCeres and only added 
```
../../../addons/ofxCeres/libs/ceres/include-osx
../../../addons/ofxCeres/libs/miniglog
../../../addons/ofxCeres/src
```
(you can add all 3 at the same time. just put them on the same line and add a space between them)

<img width="1404" alt="Screen Shot 2021-12-04 at 7 06 00 PM" src="https://user-images.githubusercontent.com/1054816/144728778-009c4882-bdeb-4307-ad3d-bebbfac54f8c.png">

That removed the Block errors but still left some `integer_sequence_algorithm.h` error. 
<img width="1400" alt="Screen Shot 2021-12-04 at 7 07 26 PM" src="https://user-images.githubusercontent.com/1054816/144728809-070de299-d538-4bb3-a119-e8b323135b98.png">

those went away when setting `C++ Language Dialect` from C++11 to C++14 in both Target and Project Build Settings.

<img width="1617" alt="Screen Shot 2021-12-04 at 7 12 28 PM" src="https://user-images.githubusercontent.com/1054816/144728821-c98178bc-3372-4e31-93cb-39594c091340.png">

Next step is to figure out what 
`'Result' is not a class, namespace, or enumeration` error is all about

**Comment by elliotwoods** [comment]
OK it seems we've got this fixed now ! Brilliant. Let's open separate issue if needed for the Result is not a calss
